client_id_prefix: "python-mqtt-"
mqtt_protocol: "tcp"
mqtt_connection_sucess_msg: "Connected with result code "
fall_detected_topic_name: "fall_detected" 
fall_detected_msg: "Ein Patient ist hingeflogen"
fall_detected_msg_subject: "Fall Detected"
mail_msg_success: "Email sent successfully"
mail_msg_failed: "Failed to send email: "