FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3-pip python3-rpi.gpio

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY alarm.py .

CMD ["python3", "alarm.py"]
